### ISSUE TITLE
Will not detect git collision?

### ISSUE THREAD

**Issue by hzsolt94** [cr-marcstevens/sha1collisiondetection#17]
As far as I understand, if two files were created to collide as git-objects, this program will mark them safe. 

Because in this case, the chosen-prefix attack will be selected to include the git header, but that header won't be there when checking the file.

It would be nice to detect collision attack on git, without the user having to create the git-object manually.
Either by checking the "headered" version of files automatically, or by providing a command-line switch to do so.

**Comment by cr-marcstevens** [comment]
Indeed it will not detect git collisions because git prepends a header. To detect git collisions it should be included in git itself. This is currently being worked on, see https://github.com/git/git/tree/pu. Alternatively, users should add the same header manually before passing to sha1dc.

Won't fix because doing additional checking with an added header does not make sense in the generic case.
